Initial Task for YouStud.
TeamDriveX/teamdrivex pull request #1
Opened 2023-11-21 16:54 UTC by bindubritto

2023-11-22 18:43 UTC, redeyed061 requested changes
Thanks, @bindubritto. I have some questions and suggestions. Also we would benefit from some linting and / or formatting and / or fixing types where they're missing.

2023-11-22 18:43 UTC, redeyed061 commented on .env
> +  # shadowDatabaseUrl = env("POSTGRES_URL_NON_POOLING") // uses a direct connection
It's better to add this file in `.gitignore` and not keep it in the repo. Also, are google credentials real here? If so, I'd recommend invalidating them, as this repo is public.

2023-11-22 18:43 UTC, redeyed061 commented on .dockerignore
> +docker-compose.yml
Nit: this file is missing a newline.

2023-11-22 18:43 UTC, redeyed061 commented on .env.example
> +# POSTGRES_PRISMA_URL="postgresql://postgres:mysecretpassword@host.docker.internal:5432/teamdrivex?schema=public&connect_timeout=300"
Do we need this comment?

2023-11-22 18:43 UTC, redeyed061 commented on .env.example
> +  # shadowDatabaseUrl = env("POSTGRES_URL_NON_POOLING") // uses a direct connection
Do we need these comments?

2023-11-22 18:43 UTC, redeyed061 commented on Dockerfile
> +# CMD ["node", "server.js"]
Since we're not going to deploy using docker, we can remove production version. Or we could use build targets in `docker-compose.yml`.

2023-11-22 18:43 UTC, redeyed061 commented on README.md
> +cp .env.example .env
Touch is redundant here, since we're copying `.env.example`.

2023-11-22 18:43 UTC, redeyed061 commented on README.md
> +docker compose up --build -d
Do we need `-d` option here?

2023-11-22 18:43 UTC, redeyed061 commented on README.md
> +docker exec -it teamdrivex-db-1 sh
Why not `docker-compose exec db sh`?

2023-11-22 18:43 UTC, redeyed061 commented on README.md
> +create database teamdrivex;
Since we're defining database environment variables in the `docker-compose.yml`, the database is created automatically when we run `docker-compose up -d` first time. So we may not need these.

2023-11-22 18:43 UTC, redeyed061 commented on README.md
> +docker exec -it teamdrivex-app-1 bash
It looks like there is no `bash` in the container. Also we can use `docker-compose exec app sh` instead.

2023-11-22 18:43 UTC, redeyed061 commented on docker-compose.yml
> +      - /app/node_modules
Do we need to mount this separately?

2023-11-22 18:43 UTC, redeyed061 commented on docker-compose.yml
> +      - pg-data:/var/lib/postgresql/data
This doesn't work, as the same directory can't be mounted twice. We need to chose one.

2023-11-22 18:43 UTC, redeyed061 commented on src/app/page.tsx
> +  const { data: session } = useSession();
If we turn this page in server-rendered, we may need to change this to `getServerSession`.

2023-11-22 18:43 UTC, redeyed061 commented on src/components/Appbar.tsx
> +"use client";
Same here. Does this need to be client-rendered?

2023-11-22 18:43 UTC, redeyed061 commented on src/components/Appbar.tsx
> +import { signIn, signOut, useSession } from "next-auth/react";
`signIn` and `signOut` imports aren't used.

2023-11-22 18:43 UTC, redeyed061 commented on src/components/SigninButton.tsx
> +import Image from "next/image";
`Image` import this not used here.

2023-11-22 18:43 UTC, redeyed061 commented on src/components/SigninButton.tsx
> +"use client";
Same about rendering on the server.

2023-11-22 18:43 UTC, redeyed061 commented on src/components/SigninButton.tsx
> +
Nit: redundant newlines.

2023-11-22 18:43 UTC, redeyed061 commented on src/components/ui/button.tsx
> +    const Comp = asChild ? Slot : "button"
What `Comp` stands for?

2023-11-22 18:43 UTC, redeyed061 commented on src/app/page.tsx
> +    }
Nit: looks like this is over-indented.

2023-11-23 03:24 UTC, bindubritto commented on .env
> +  # shadowDatabaseUrl = env("POSTGRES_URL_NON_POOLING") // uses a direct connection
I did this so that, you can run smoothly. Anyways, removing it.

2023-11-23 03:24 UTC, bindubritto commented on .dockerignore
> +docker-compose.yml
Okay.

2023-11-23 03:24 UTC, bindubritto commented on .env.example
> +# POSTGRES_PRISMA_URL="postgresql://postgres:mysecretpassword@host.docker.internal:5432/teamdrivex?schema=public&connect_timeout=300"
Nope. Removing it.

2023-11-23 03:24 UTC, bindubritto commented on .env.example
> +  # shadowDatabaseUrl = env("POSTGRES_URL_NON_POOLING") // uses a direct connection
Nope.

2023-11-23 03:26 UTC, bindubritto commented on Dockerfile
> +# CMD ["node", "server.js"]
Okay. Removing it.

2023-11-23 03:27 UTC, bindubritto commented on src/components/SigninButton.tsx
> +import Image from "next/image";
Using linting save this type of mistakes. Resolved.

2023-11-23 03:27 UTC, bindubritto commented on src/components/SigninButton.tsx
> +
Solved.

2023-11-23 03:29 UTC, bindubritto commented on src/components/ui/button.tsx
> +    const Comp = asChild ? Slot : "button"
Component.

2023-11-27 02:15 UTC, bindubritto commented on README.md
> +docker compose up --build -d
It's actually a matter of choice. You can run either in detached mood or not.

2023-11-27 02:55 UTC, bindubritto commented on README.md
> +docker exec -it teamdrivex-db-1 sh
Yeah, it also works as well.

2023-11-27 17:03 UTC, redeyed061 commented on docker-compose.yml
> +      - /app/node_modules
Nevermind, looks like it's a common practice.

2023-11-27 17:04 UTC, redeyed061 commented on package.json
> +    "clsx": "^2.0.0",
Nevermind, looks like it's coming from shadcn/ui initialization.

2023-11-27 17:05 UTC, redeyed061 commented on src/app/page.tsx
> +"use client";
Just to clarify why I'm asking: AFAIK it's advised to keep client-side components as deep in the component tree as possible.

2023-11-28 03:09 UTC, bindubritto commented on README.md
> +create database teamdrivex;
mmm, as per my understanding, the default database is postgres, not teamdrivex. So, if you want to connect with teamdrivex database, you need to create that database.

2023-11-28 03:11 UTC, bindubritto commented on README.md
> +docker exec -it teamdrivex-app-1 bash
Yes. My bad.

2023-11-28 03:11 UTC, bindubritto commented on components.json
> +}
Resolved.

2023-11-28 03:16 UTC, bindubritto commented on next.config.js
> +  output: 'standalone'
To fetch the image of your google account, we need to add these lines in `next.config.js`

`output: 'standalone'` this is not mandatory, in case of docker build, I read in some github issue pages that it is required to generate build in a `standalone` mode.

2023-11-28 03:17 UTC, bindubritto commented on src/app/page.tsx
> +  const { data: session } = useSession();
Yes. You're right.

2023-11-28 03:18 UTC, bindubritto commented on src/app/page.tsx
> +    }
Haha. This time, linting saved me.

2023-11-28 03:18 UTC, bindubritto commented on src/components/Appbar.tsx
> +import { signIn, signOut, useSession } from "next-auth/react";
Removed unnecessary import.

2023-11-28 03:22 UTC, bindubritto commented on src/app/page.tsx
> +"use client";
Okay, looking into it.

2023-11-28 03:32 UTC, bindubritto commented on docker-compose.yml
> +      - pg-data:/var/lib/postgresql/data
Removed.

2023-11-28 04:33 UTC, bindubritto commented on src/app/api/auth/[...nextauth]/route.ts
> +    strategy: "jwt",
Why we will use session in DB instead? we can use redis for session management.

2023-11-28 04:35 UTC, bindubritto commented on src/app/api/auth/[...nextauth]/route.ts
> +      profile(profile) {
Please elaborate. Or give some warning message here. Is there any linting warning, then we can remove that as well. But give us the some message.

2023-11-28 04:37 UTC, bindubritto commented on src/app/page.tsx
> +"use client";
Yes, you're right. We'll do that.

2023-11-28 04:38 UTC, bindubritto commented on src/app/page.tsx
> +  const { data: session } = useSession();
We will change that.

2023-11-28 04:38 UTC, bindubritto commented on src/app/page.tsx
>  import Image from 'next/image'
Linting saved me.

2023-11-28 16:37 UTC, redeyed061 commented on README.md
> +create database teamdrivex;
That's right, @bindubritto. However `postgres:15-alpine` creates automatically whatever database is specified in `POSTGRES_DB` environment variable. :slightly_smiling_face: This command has failed for me when I was testing, since the DB was created already.

2023-11-28 16:38 UTC, redeyed061 commented on next.config.js
> +  output: 'standalone'
Ah, makes sense @bindubritto.

2023-11-28 16:43 UTC, redeyed061 commented on src/app/api/auth/[...nextauth]/route.ts
> +    strategy: "jwt",
@bindubritto, honestly I don't know what's better in Next.js context. I can imagine JWT be more fragile in server-side environment, but I perfectly can be wrong. I'm asking because I see that we [create a DB table](https://github.com/TeamDriveX/teamdrivex/blob/fd6947648d18604b63de2b1bb2a232e5a797daf3/prisma/migrations/20231117032642_init/migration.sql#L20-L27) for sessions in the migration. If it has been added automatically, it's fine to leave it as is and think later. But if not, isn't it redundant?

2023-11-28 16:44 UTC, redeyed061 commented on src/app/api/auth/[...nextauth]/route.ts
> +      profile(profile) {
@bindubritto, sorry, what I meant is missing TypeScript types. My IDE shows them. It'd be nice to enable some strict type checking and properly type _everything_, but feel free to ignore this for now (I was going to set up automated CI checks after we merge this PR).

2023-11-28 16:48 UTC, redeyed061 commented on src/app/page.tsx
> +  const { data: session } = useSession();
@bindubritto, just an idea based on what I saw in the internet: you can break down this component. The page will be server-rendered, and the part requiring `useSession` client-rendered. However, please what you thing will be better.

2023-11-28 16:51 UTC, redeyed061 commented on src/components/SigninButton.tsx
> +"use client";
Note: after re-reading some docs, we after all may have to keep the button client-rendered. As soon as it's gonna be deep in the component tree - it's fine. However, I'd rely on your opinion, I don't have much experience with Next.js.

2023-11-30 16:42 UTC, bindubritto commented on README.md
> +create database teamdrivex;
Okay Cool. Removing it.

2023-11-30 17:26 UTC, bindubritto commented on src/app/page.tsx
> +"use client";
Resolved. Make this component to server rendered component.

2023-11-30 17:27 UTC, bindubritto commented on src/app/page.tsx
> +  const { data: session } = useSession();
Yes. Convert this to server rendered component.

2023-11-30 17:36 UTC, bindubritto commented on src/components/Appbar.tsx
> +"use client";
Yes. Modified this to server render component. :-D

2023-11-30 17:38 UTC, bindubritto commented on src/app/admin/page.tsx
> +const AdminPage = async () => {
Now converted others to arrow functions.

2023-11-30 17:51 UTC, bindubritto commented on src/app/api/auth/[...nextauth]/route.ts
> +      profile(profile) {
Okay, I'm ignoring this file now. I will do some R&D and let you know.

2023-11-30 19:57 UTC, redeyed061 commented on docker-compose.yml
> +      - pg-data:/var/lib/postgresql/data
@bindubritto, it's still there. :slightly_smiling_face: Don't bother with fixing though, I'll do this when merge the PR.

2023-11-30 20:00 UTC, redeyed061 commented on package.json
> +    "lint": "yarn add -D prettier && yarn add -D babel-eslint && npx install-peerdeps --dev eslint-config-airbnb && yarn add -D eslint-config-prettier eslint-plugin-prettier"
@bindubritto, we already have all these packages under `devDependencies`, so they are installed during project installation.

2023-11-30 20:04 UTC, merged